{% set name = "stack_data" %}
{% set version = "0.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 95eb784942e861a3d80efd549ff9af6cf847d88343a12eb681d7157cfcb6e32b

build:
  number: 0
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv '
  noarch: python

requirements:
  host:
    - pip
    - python >=3.5
    - setuptools >=44
    - setuptools_scm >=3.4.3
  run:
    - asttokens
    - executing
    - pure_eval
    - python >=3.5

test:
  imports:
    - stack_data
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://github.com/alexmojaki/stack_data
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Extract data from python stack frames and tracebacks for informative displays
  doc_url: http://github.com/alexmojaki/stack_data
  dev_url: http://github.com/alexmojaki/stack_data

extra:
  recipe-maintainers:
    - alexmojaki
